### PR TITLE
Update installation-guide.md

### PR DESCRIPTION
**Pull request by Samaritan4186**
Add the instructions to create a USB installer. Also combs through the instructions to fix some errors I found during my installation.

### CODE REVIEW

**Comment by gorouflex** [comment]
ok looks good

**Comment by gorouflex** [comment]
also i edit something on your PR because RDR images it's not Mac Recovery Online that you give
This method will be introduced in Aug 2023

**Comment by gorouflex** [comment]
i am building it you'll know later

**Comment by Samaritan4186** [comment]
Okay perfect! Can you give me a basic idea of what it is though? I can't find any documentation?

Inviato da Outlook per Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by gorouflex** [comment]
ok i am publish the beta guide next 5 min

**Comment by Samaritan4186** [comment]
Alright bro, btw will upload my efi in a bit, it's quite diff to yours so I wouldn't merge unless it also boots for you, or maybe we can merge it under a specific `ThinkPad` branch?

Inviato da Outlook per Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by gorouflex** [comment]
https://github.com/gorouflex/amdlaptophackintosh/blob/main/rdr-guide.md
Yes you can create one branch for ThinkPad and create a PR

**Comment by gorouflex** [comment]
@Samaritan4186 hey check out again my rdr guide also add friend in Discord 
Username: gorouflex
thanks!

**Comment by Samaritan4186** [comment]
Friend request sent

**Pull request merged**
